# Generated by Django 5.0.6 on 2024-07-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0002_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
